use strum_macros::EnumIter;

#[derive(PartialEq, EnumIter)]
pub enum Language {
    EN,
    ES,
    RU,
    AF,
    ACH,
    AK,
    AM,
    AR,
    AZ,
    BE,
    BEM,
    BG,
    BH,
    BN,
    BR,
    BS,
    CA,
    CHR,
    CKB,
    CO,
    CRS,
    CS,
    CY,
    DA,
    DE,
    EE,
    EL,
    EO,
    ES419,
    ET,
    EU,
    FA,
    FI,
    FO,
    FR,
    FY,
    GA,
    GAA,
    GD,
    GL,
    GN,
    GU,
    HA,
    HAW,
    HI,
    HR,
    HT,
    HU,
    HY,
    IA,
    ID,
    IG,
    IS,
    IT,
    IW,
    JA,
    JW,
    KA,
    KG,
    KK,
    KM,
    KN,
    KO,
    KRI,
    KU,
    KY,
    LA,
    LG,
    LN,
    LO,
    LOZ,
    LT,
    LUA,
    LV,
    MFE,
    MG,
    MI,
    MK,
    ML,
    MN,
    MO,
    MR,
    MS,
    MT,
    NE,
    NL,
    NN,
    NO,
    NSO,
    NY,
    NYN,
    OC,
    OM,
    OR,
    PA,
    PCM,
    PL,
    PS,
    PTBR,
    PTPT,
    QU,
    RM,
    RN,
    RO,
    RW,
    SD,
    SH,
    SI,
    SK,
    SL,
    SN,
    SO,
    SQ,
    SR,
    SRME,
    ST,
    SU,
    SV,
    SW,
    TA,
    TE,
    TG,
    TH,
    TI,
    TK,
    TL,
    TN,
    TO,
    TR,
    TT,
    TUM,
    TW,
    UG,
    UK,
    UR,
    UZ,
    VI,
    WO,
    XH,
    XXBORK,
    XXELMER,
    XXHACKER,
    XXKLINGON,
    XXPIRATE,
    YI,
    YO,
    ZHCN,
    ZHTW,
    ZU,
}

impl Language {
    pub(crate) fn as_str(&self) -> &'static str {
        match self {
            Language::EN => "English",
            Language::ES => "Spanish",
            Language::RU => "Russian",
            Language::AF => "Afrikaans",
            Language::ACH => "Acholi",
            Language::AK => "Akan",
            Language::AM => "Amharic",
            Language::AR => "Arabic",
            Language::AZ => "Azerbaijani",
            Language::BE => "Belarusian",
            Language::BEM => "Bemba",
            Language::BG => "Bulgarian",
            Language::BH => "Bihari",
            Language::BN => "Bengali",
            Language::BR => "Breton",
            Language::BS => "Bosnian",
            Language::CA => "Catalan",
            Language::CHR => "Cherokee",
            Language::CKB => "Central Kurdish",
            Language::CO => "Corsican",
            Language::CRS => "Seselwa Creole French",
            Language::CS => "Czech",
            Language::CY => "Welsh",
            Language::DA => "Danish",
            Language::DE => "German",
            Language::EE => "Ewe",
            Language::EL => "Greek",
            Language::EO => "Esperanto",
            Language::ES419 => "Latin American Spanish",
            Language::ET => "Estonian",
            Language::EU => "Basque",
            Language::FA => "Persian",
            Language::FI => "Finnish",
            Language::FO => "Faroese",
            Language::FR => "French",
            Language::FY => "Frisian",
            Language::GA => "Irish",
            Language::GAA => "Ga",
            Language::GD => "Scottish Gaelic",
            Language::GL => "Galician",
            Language::GN => "Guarani",
            Language::GU => "Gujarati",
            Language::HA => "Hausa",
            Language::HAW => "Hawaiian",
            Language::HI => "Hindi",
            Language::HR => "Croatian",
            Language::HT => "Haitian Creole",
            Language::HU => "Hungarian",
            Language::HY => "Armenian",
            Language::IA => "Interlingua",
            Language::ID => "Indonesian",
            Language::IG => "Igbo",
            Language::IS => "Icelandic",
            Language::IT => "Italian",
            Language::IW => "Hebrew",
            Language::JA => "Japanese",
            Language::JW => "Javanese",
            Language::KA => "Georgian",
            Language::KG => "Kongo",
            Language::KK => "Kazakh",
            Language::KM => "Khmer",
            Language::KN => "Kannada",
            Language::KO => "Korean",
            Language::KRI => "Krio",
            Language::KU => "Kurdish",
            Language::KY => "Kyrgyz",
            Language::LA => "Latin",
            Language::LG => "Ganda",
            Language::LN => "Lingala",
            Language::LO => "Lao",
            Language::LOZ => "Lozi",
            Language::LT => "Lithuanian",
            Language::LUA => "Luba-Katanga",
            Language::LV => "Latvian",
            Language::MFE => "Morisyen",
            Language::MG => "Malagasy",
            Language::MI => "Maori",
            Language::MK => "Macedonian",
            Language::ML => "Malayalam",
            Language::MN => "Mongolian",
            Language::MO => "Moldavian",
            Language::MR => "Marathi",
            Language::MS => "Malay",
            Language::MT => "Maltese",
            Language::NE => "Nepali",
            Language::NL => "Dutch",
            Language::NN => "Norwegian Nynorsk",
            Language::NO => "Norwegian",
            Language::NSO => "Northern Sotho",
            Language::NY => "Nyanja",
            Language::NYN => "Nyankole",
            Language::OC => "Occitan",
            Language::OM => "Oromo",
            Language::OR => "Oriya",
            Language::PA => "Punjabi",
            Language::PCM => "Nigerian Pidgin",
            Language::PL => "Polish",
            Language::PS => "Pashto",
            Language::PTBR => "Portuguese (Brazil)",
            Language::PTPT => "Portuguese (Portugal)",
            Language::QU => "Quechua",
            Language::RM => "Romansh",
            Language::RN => "Kirundi",
            Language::RO => "Romanian",
            Language::RW => "Kinyarwanda",
            Language::SD => "Sindhi",
            Language::SH => "Serbo-Croatian",
            Language::SI => "Sinhala",
            Language::SK => "Slovak",
            Language::SL => "Slovenian",
            Language::SN => "Shona",
            Language::SO => "Somali",
            Language::SQ => "Albanian",
            Language::SR => "Serbian",
            Language::SRME => "Montenegrin",
            Language::ST => "Southern Sotho",
            Language::SU => "Sundanese",
            Language::SV => "Swedish",
            Language::SW => "Swahili",
            Language::TA => "Tamil",
            Language::TE => "Telugu",
            Language::TG => "Tajik",
            Language::TH => "Thai",
            Language::TI => "Tigrinya",
            Language::TK => "Turkmen",
            Language::TL => "Tagalog",
            Language::TN => "Tswana",
            Language::TO => "Tongan",
            Language::TR => "Turkish",
            Language::TT => "Tatar",
            Language::TUM => "Tumbuka",
            Language::TW => "Twi",
            Language::UG => "Uighur",
            Language::UK => "Ukrainian",
            Language::UR => "Urdu",
            Language::UZ => "Uzbek",
            Language::VI => "Vietnamese",
            Language::WO => "Wolof",
            Language::XH => "Xhosa",
            Language::XXBORK => "Bork, bork, bork!",
            Language::XXELMER => "Elmer Fudd",
            Language::XXHACKER => "Hacker",
            Language::XXKLINGON => "Klingon",
            Language::XXPIRATE => "Pirate",
            Language::YI => "Yiddish",
            Language::YO => "Yoruba",
            Language::ZHCN => "Chinese (Simplified)",
            Language::ZHTW => "Chinese (Traditional)",
            Language::ZU => "Zulu",
        }
    }

    pub(crate) fn as_code(&self) -> &'static str {
        match self {
            Language::AF => "af",
            Language::ACH => "ach",
            Language::AK => "ak",
            Language::AM => "am",
            Language::AR => "ar",
            Language::AZ => "az",
            Language::BE => "be",
            Language::BEM => "bem",
            Language::BG => "bg",
            Language::BH => "bh",
            Language::BN => "bn",
            Language::BR => "br",
            Language::BS => "bs",
            Language::CA => "ca",
            Language::CHR => "chr",
            Language::CKB => "ckb",
            Language::CO => "co",
            Language::CRS => "crs",
            Language::CS => "cs",
            Language::CY => "cy",
            Language::DA => "da",
            Language::DE => "de",
            Language::EE => "ee",
            Language::EL => "el",
            Language::EN => "en",
            Language::EO => "eo",
            Language::ES => "es",
            Language::ES419 => "es-419",
            Language::ET => "et",
            Language::EU => "eu",
            Language::FA => "fa",
            Language::FI => "fi",
            Language::FO => "fo",
            Language::FR => "fr",
            Language::FY => "fy",
            Language::GA => "ga",
            Language::GAA => "gaa",
            Language::GD => "gd",
            Language::GL => "gl",
            Language::GN => "gn",
            Language::GU => "gu",
            Language::HA => "ha",
            Language::HAW => "haw",
            Language::HI => "hi",
            Language::HR => "hr",
            Language::HT => "ht",
            Language::HU => "hu",
            Language::HY => "hy",
            Language::IA => "ia",
            Language::ID => "id",
            Language::IG => "ig",
            Language::IS => "is",
            Language::IT => "it",
            Language::IW => "iw",
            Language::JA => "ja",
            Language::JW => "jw",
            Language::KA => "ka",
            Language::KG => "kg",
            Language::KK => "kk",
            Language::KM => "km",
            Language::KN => "kn",
            Language::KO => "ko",
            Language::KRI => "kri",
            Language::KU => "ku",
            Language::KY => "ky",
            Language::LA => "la",
            Language::LG => "lg",
            Language::LN => "ln",
            Language::LO => "lo",
            Language::LOZ => "loz",
            Language::LT => "lt",
            Language::LUA => "lua",
            Language::LV => "lv",
            Language::MFE => "mfe",
            Language::MG => "mg",
            Language::MI => "mi",
            Language::MK => "mk",
            Language::ML => "ml",
            Language::MN => "mn",
            Language::MO => "mo",
            Language::MR => "mr",
            Language::MS => "ms",
            Language::MT => "mt",
            Language::NE => "ne",
            Language::NL => "nl",
            Language::NN => "nn",
            Language::NO => "no",
            Language::NSO => "nso",
            Language::NY => "ny",
            Language::NYN => "nyn",
            Language::OC => "oc",
            Language::OM => "om",
            Language::OR => "or",
            Language::PA => "pa",
            Language::PCM => "pcm",
            Language::PL => "pl",
            Language::PS => "ps",
            Language::PTBR => "pt-BR",
            Language::PTPT => "pt-PT",
            Language::QU => "qu",
            Language::RM => "rm",
            Language::RN => "rn",
            Language::RO => "ro",
            Language::RU => "ru",
            Language::RW => "rw",
            Language::SD => "sd",
            Language::SH => "sh",
            Language::SI => "si",
            Language::SK => "sk",
            Language::SL => "sl",
            Language::SN => "sn",
            Language::SO => "so",
            Language::SQ => "sq",
            Language::SR => "sr",
            Language::SRME => "sr-ME",
            Language::ST => "st",
            Language::SU => "su",
            Language::SV => "sv",
            Language::SW => "sw",
            Language::TA => "ta",
            Language::TE => "te",
            Language::TG => "tg",
            Language::TH => "th",
            Language::TI => "ti",
            Language::TK => "tk",
            Language::TL => "tl",
            Language::TN => "tn",
            Language::TO => "to",
            Language::TR => "tr",
            Language::TT => "tt",
            Language::TUM => "tum",
            Language::TW => "tw",
            Language::UG => "ug",
            Language::UK => "uk",
            Language::UR => "ur",
            Language::UZ => "uz",
            Language::VI => "vi",
            Language::WO => "wo",
            Language::XH => "xh",
            Language::XXBORK => "xx-bork",
            Language::XXELMER => "xx-elmer",
            Language::XXHACKER => "xx-hacker",
            Language::XXKLINGON => "xx-klingon",
            Language::XXPIRATE => "xx-pirate",
            Language::YI => "yi",
            Language::YO => "yo",
            Language::ZHCN => "zh-CN",
            Language::ZHTW => "zh-TW",
            Language::ZU => "zu",
        }
    }
}
